version: '3.8'

services: 
  postgres: 
    image: 'postgres'
    ports: 
      - 5434:5432
    environment:
      POSTGRES_DB: gobarberapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres